version: "2"
authtoken: 31XaV1VBqTp12AujuDnPYoJra48_5ALormMPAtpXC9YwEJYE2

tunnels:
  chatbot:
    addr: 8000
    proto: http
    bind_tls: true
    inspect: true
    
  chatbot-alt:
    addr: 8000
    proto: http
    hostname: dr-meenakshi-tomar-chatbot.ngrok.io
    bind_tls: true